version: '3.7'

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.conan
    command: tail -f /dev/null
    working_dir: /app
    volumes:
      - .:/app
    user: 1000:1000
  mysql:
    image: mysql:8
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_RANDOM_ROOT_PASSWORD: true
    ports:
      - 3306:3306
